apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.capi.namespace }}
  labels:
    service: capi
  name: capi-metrics
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8381
  type: ClusterIP
  selector:
    service: {{ .Values.capi.name }}