name: capi
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 21
    - uses: actions/checkout@v3.5.3

    - name: Set up Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
    - name: Set Release version env variable
      run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn package  -DskipTests --file pom.xml
    - name: Docker login
      run: |
          docker login -u surisoft+surisoft -p ${{ secrets.QUAY_IO_TOKEN }}
    - name: Build and push multi-platform image
      run: |
        docker buildx create --use
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          --build-arg "CAPI_VERSION=${{ env.RELEASE_VERSION }}" \
          --file Dockerfile \
          --tag quay.io/surisoft/capi:${{ env.RELEASE_VERSION }} \
          --tag quay.io/surisoft/capi:latest \
          --push
